from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3eba68808c2a'
down_revision = 'b2f969a3a3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        # Add new columns as nullable initially to avoid conflicts
        batch_op.add_column(sa.Column('total_pending_requests', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_approved_requests', sa.Float(), nullable=True))

        # Ensure total_donations is not nullable
        batch_op.alter_column('total_donations',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

        # Drop the old column 'pending_donations'
        batch_op.drop_column('pending_donations')

    # After adding columns, we update all existing rows to have default values
    op.execute("UPDATE reports SET total_pending_requests = 0.0 WHERE total_pending_requests IS NULL")
    op.execute("UPDATE reports SET total_approved_requests = 0.0 WHERE total_approved_requests IS NULL")

    # Alter columns to enforce NOT NULL constraint
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('total_pending_requests', nullable=False)
        batch_op.alter_column('total_approved_requests', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        # Re-add the 'pending_donations' column (to reverse the migration)
        batch_op.add_column(sa.Column('pending_donations', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

        # Make 'total_donations' column nullable again
        batch_op.alter_column('total_donations',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

        # Drop the new columns
        batch_op.drop_column('total_approved_requests')
        batch_op.drop_column('total_pending_requests')

    # ### end Alembic commands ###

