"""Remove confirm passsword column

Revision ID: 7affeb7fe4a4
Revises: e2373f7cda09
Create Date: 2024-11-06 22:59:10.767620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7affeb7fe4a4'
down_revision = 'e2373f7cda09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirm_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_password', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
