"""Added donation_request_id to Donations table

Revision ID: 9314be256543
Revises: 2f53a28fde73
Create Date: 2024-11-09 16:22:10.401915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '9314be256543'
down_revision = '2f53a28fde73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        if 'donation_request_id' not in [column['name'] for column in inspect(op.get_bind()).get_columns('donations')]:
          op.add_column('donations', sa.Column('donation_request_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'donation_requests', ['donation_request_id'], ['request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('donation_request_id')

    # ### end Alembic commands ###
